name: Run checks

on:
  push:
    branches:
      - main
      - 'BA**'
  pull_request:
    branches:
      - main
      - 'BA**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8-print black anybadge
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Pylint
      run: |
        pylint --rcfile=.pylintrc --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee pylint.txt
    - name: Lint with flake8
      run: |
        mypy --install-types --non-interactive .
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run black
      run: |
        black . --line-length=79 --include='\.pyi?$' --check
    - name: Test with pytest
      run: |
        pytest
